### ISSUE TITLE
Use of `resId` in `format/formatToParts`

### ISSUE THREAD

**Issue by zbraniecki** [dminor/proposal-intl-messageformat#1]
In Mozilla systems (DTD & Fluent), once the context is created and messages are listed in it, there is no information about which resource the message came from.

The consumer of the context, either calling for a message to be formatted, or referencing one message from another, does not know which resource provided a given message.

It seems to me that this proposal (and MF2.0 proposal) changes it. It is now required to explicitly state the resource id of the message we are retrieving or referencing.

I'm not sure what are the implications of that change, but I wanted to start this discussion to explicitly call out that change. Since DTD/Fluent are the only known to us systems that have prior art on message references and contexts (as far as I'm aware), that means that the model of a shared namespace for all resources in context is the only one we have experience with in production.

I think we should do our due diligence to document why are we diverging from that prior art, what is the value proposition of such diversion and try to predict what are the tradeoffs of such change.

One that comes to my mind is that in Firefox we often had ability to compose a context from multiple resources and as long as the total sum of the IDs was the same, the context was equally complete.
For example, a context with `["common/menus.dtd", "browser/preferences.dtd"]` could be constructed and based on some runtime parameters a difference context - `["experimental/menus.dtd", "browser/preferences.dtd"]` could be used in its place and as long as the two menus.dtd provided the same list of IDs, the stability of the system was preserved.

It seems to me that such behavior will be much affected in the MF2.0 model, since now any such change would require changes to message references in `browser/preferences.dtd` *and* all callsites that requrest messages from `menus.dtd`.

Second implication is consistency between JS MF2.0 and DOM bindings. Does this change mean that for declarative API we'll also require resources to be listed?

```html
<button l10n-resid="browser/menus.mf2.0" l10n-id="open-window" />
```

**Comment by eemeli** [comment]
Requiring the resourced identifier should not be required if all resources use the same, as is effectively done in Fluent; that's an oversight for the current `formatToParts()` interface. The situation should get clarified by #3.
